### ISSUE TITLE
Strange behavior with -e switch

### ISSUE THREAD

**Issue by samhunter** [dstreett/FLASH2#1]
The -e switch produces strange behavior and doesn't appear to set the "outie" overlap correctly except at values <= 9.

For example:
../FLASH2/flash2 --max-overlap 350 -m 20 -e 15 --allow-outies -t 3
[FLASH] Parameters:
[FLASH]     Min overlap:           20
[FLASH]     Min overlap outie:     40
[FLASH]     Max overlap:           350
[FLASH]     Max mismatch density:  0.250000
[FLASH]     Allow "outie" pairs:   true
[FLASH]     Cap mismatch quals:    false
[FLASH]     Combiner threads:      3
[FLASH]     Input format:          FASTQ, phred_offset=33
[FLASH]     Output format:         FASTQ, phred_offset=33

../FLASH2/flash2 --max-overlap 350 -m 20 -e 20 
[FLASH] Parameters:
[FLASH]     Min overlap:           20
[FLASH]     Min overlap outie:     70
[FLASH]     Max overlap:           350
[FLASH]     Max mismatch density:  0.250000
[FLASH]     Allow "outie" pairs:   true
[FLASH]     Cap mismatch quals:    false
[FLASH]     Combiner threads:      3
[FLASH]     Input format:          FASTQ, phred_offset=33
[FLASH]     Output format:         FASTQ, phred_offset=33

../FLASH2/flash2 --max-overlap 350 -m 20 -e 10
[FLASH] Parameters:
[FLASH]     Min overlap:           20
[FLASH]     Min overlap outie:     35
[FLASH]     Max overlap:           350
[FLASH]     Max mismatch density:  0.250000
[FLASH]     Allow "outie" pairs:   true
[FLASH]     Cap mismatch quals:    false
[FLASH]     Combiner threads:      3
[FLASH]     Input format:          FASTQ, phred_offset=33
[FLASH]     Output format:         FASTQ, phred_offset=33

../FLASH2/flash2 --max-overlap 350 -m 20 -e 9 --allow-outies -t 3
[FLASH] Parameters:
[FLASH]     Min overlap:           20
[FLASH]     Min overlap outie:     9
[FLASH]     Max overlap:           350
[FLASH]     Max mismatch density:  0.250000
[FLASH]     Allow "outie" pairs:   true
[FLASH]     Cap mismatch quals:    false
[FLASH]     Combiner threads:      3
[FLASH]     Input format:          FASTQ, phred_offset=33
[FLASH]     Output format:         FASTQ, phred_offset=33

Note:
 ../FLASH2/flash2 --version
FLASH v2.2.00
Copyright (C) 2012 Tanja Magoc
Copyright (C) 2012, 2013, 2014 Eric Biggers
Modifications 2015 David Streett
License GPLv3+; GNU GPL version 3 or later http://gnu.org/licenses/gpl.html.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Report bugs to flash.comment@gmail.com or https://sourceforge.net/p/flashpage/bugs

Also:

YESSSSSSSSSSSSS first in the comments section!!!

thanks :)

**Comment by dstreett** [comment]
Thanks, @samhunter! There was an error when using strtol(), I accidently put the default number (35) as the base, instead of 10. That could cause for some odd numbers! Thanks for the great catch and it is now all fixed.

Also, congrats for the first comment!

**Comment by samhunter** [comment]
Thanks!
