### ISSUE TITLE
-d flag in windows does not work

### ISSUE THREAD

**Issue by RobinVanSchendel** [dstreett/FLASH2#14]
I receive error messages like:

[FLASH] ERROR: Failed to create directory "E:": Permission denied
[FLASH] FLASH did not complete successfully; exiting with failure status (1)

this is my command:
C:\Users\rvanschendel\Downloads\FLASH-1.2.11-windows-bin\flash.exe E:\testHiSeqMerge\HMKV7DMXX_103911-001-001_1_WT_CRU_locus_L7_L001_R1.fastq.gz E:\testHiSeqMerge\HMKV7DMXX_103911-001-001_1_WT_CRU_locus_L7_L001_R2.fastq.gz -z -t 1 -d E:\testHiSeqMerge -o HMKV7DMXX_103911-001-001_1_WT_CRU_locus_L7_L001_R1.fastq.gz_assembled.fastq.gz

Likely a windows vs linux path problem. If I don't use the -d option it works fine

**Comment by samhunter** [comment]
Hi @RobinVanSchendel , I think you might be using the windows binary provided here: https://ccb.jhu.edu/software/FLASH/

To the best of my knowledge, FLASH2 never supported Windows and an exe was never released for Windows users. 

Some of the ideas and changes that were implemented in FLASH2 (a revision of the original FLASH from JHU) have been implemented in our newer project, HTStream. FLASH2 is no longer supported.

HTStream is available here, but please note that Windows is also not supported by HTStream:
https://github.com/ibest/HTStream
